<?php 

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');//get current product

$helper = $this->helper("Graduation\QuickorderingSystem\Helper\Data");
$buttonTitle = $helper->getConfig('quickorder/general/button_title');
$postParams = [
            'id' => $product->getId(),
            'sku' => $product->getSku(),
        	];
?>
<div class="">
    <button type="submit"
            title="<?php echo $block->escapeHtml(__($buttonTitle)); ?>"
            class="quickorder primary"
            id="product-quickorder-button"
            >
        <span><?php /* @noEscape */ echo __($buttonTitle) ?></span>
    </button>
</div>

<div data-role="focusable-scope" id="popup_modal">
    <div id="popupmodal" style="">
        <div style="margin-top:20px;">
            <table id="quickorder" border="0" cellspacing="0" cellpadding="0">
                <tbody>
                <input name="quickorder_sku" id="quickorder_sku_<?php echo $postParams['sku']?>" value="<?php echo $block->getProductParams($product)['sku']?>" type="text" hidden>
                <tr>
                    <td style="width:20%;"><strong>Name*</strong></td>
                    <td>:</td>
                    <td>
                        <input name="quickorder_name" id="quickorder_name" class="required-entry" value="" style="width:80%;" type="text">
                    </td>
                </tr>
                <tr>
                    <td style="width:20%;"><strong>Phone*</strong></td>
                    <td>:</td>
                    <td>
                        <input name="quickorder_phone" id="quickorder_phone" class="required-entry" value="" style="width:80%;" type="text"><br/>
                    </td>
                </tr>
                <tr>
                    <td style="width:20%;"><strong>Email</strong></td>
                    <td>:</td>
                    <td>
                        <input name="quickorder_email" type="email" id="quickorder_email" class="" value="" style="width:80%;" type="email"><br/>
                    </td>
                </tr>
                </tbody>
            </table>
            <div class="" id="submit_quickorder">
                <button type="submit"><?php echo __('Send'); ?></button>
            </div>
        </div>
    </div>
</div>

<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Quick Order Information',
                buttons: []
            };

            var popup = modal(options, $('#popup_modal'));
            $("#product-quickorder-button").on('click',function(){
                $("#popup_modal").modal("openModal");
                // $(this).remove();
            });

            var url = '<?php echo $block->getAjax(); ?>';

            $("#submit_quickorder").on('click',function(){
                var sku     = $("#quickorder_sku_<?php echo $postParams['sku']?>").val();
                var name    = $("#quickorder_name").val();
                var phone   = $("#quickorder_phone").val();
                var email   = $("#quickorder_email").val();
                // console.log(url);
                // console.log(name);
                // console.log(sku);
                // console.log(phone);
                // console.log(email);
                
                $.ajax({
                type: "POST",
                url: url + '?name=' + name  + '&mail=' + email + '&phone=' + phone + '&product_sku=' + sku,
                contentType: false,
                cache: false,
                processData: false,
                data: {form_key: '<?php echo $block->getFormKey() ?>'},
                
                success: function () {
                  $("#popup_modal").modal("closeModal");
                    // console.log('dddddddddddd');
                },  

                error: function(XMLHttpRequest, textStatus, errorThrown) { 
                    alert("Status: " + textStatus); alert("Error: " + errorThrown); 
                },  

                showLoader: true
                });
                
            });
        }
    );
</script>