<?php 
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');//get current product
?>
<?php $helper = $this->helper("Graduation\QuickorderingSystem\Helper\Data"); ?>
<?php $buttonTitle = $helper->getConfig('quickorder/general/button_title'); ?>
<?php $postParams = [
            'id' => $product->getId(),
            'sku' => $product->getSku(),
        ];
print_r($postParams);?>
<div class="">
    <button type="submit"
            title="<?php echo $block->escapeHtml(__($buttonTitle)); ?>"
            class="quickorder primary"
            id="product-callback-button"
            >
        <span><?php /* @noEscape */ echo __($buttonTitle) ?> <?php /* @noEscape */ print_r($postParams['id']) ?><?php echo $block->getAjax(); ?> </span>
    </button>
</div>

<div data-role="focusable-scope" id="popup_modal">
    <div id="popupmodal" style="">
        <div style="margin-top:20px;">
            <table id="callback" border="0" cellspacing="0" cellpadding="0">
                <tbody>
                <input name="callback_sku" id="callback_sku_<?php echo $postParams['sku']?>" value="<?php echo $block->getProductParams($product)['sku']?>" type="text" hidden>
                <tr>
                    <td style="width:20%;"><strong>Name*</strong></td>
                    <td>:</td>
                    <td>
                        <input name="callback_name" id="callback_name" class="required-entry" value="" style="width:80%;" type="text">
                    </td>
                </tr>
                <tr>
                    <td style="width:20%;"><strong>Phone*</strong></td>
                    <td>:</td>
                    <td>
                        <input name="callback_phone" id="callback_phone" class="required-entry" value="" style="width:80%;" type="text"><br/>
                    </td>
                </tr>
                <tr>
                    <td style="width:20%;"><strong>Email</strong></td>
                    <td>:</td>
                    <td>
                        <input name="callback_email" type="email" id="callback_email" class="" value="" style="width:80%;" type="email"><br/>
                    </td>
                </tr>
                </tbody>
            </table>
            <div class="save_data" id="submit_button">
                <button type="submit"><?php echo __('Send'); ?></button>
            </div>
        </div>
    </div>
</div>

<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Quick Order Information',
                buttons: []
            };

            var popup = modal(options, $('#popup_modal'));
            $("#product-callback-button").on('click',function(){
                $("#popup_modal").modal("openModal");
                // $(this).remove();
            });

            var url = '<?php echo $block->getAjax(); ?>';

            $("#submit_button").on('click',function(){
                var sku    = $("#callback_sku_<?php echo $postParams['sku']?>").val();
                var name    = $("#callback_name").val();
                var phone   = $("#callback_phone").val();
                var email   = $("#callback_email").val();
                console.log(url);
                console.log(name);
                console.log(sku);
                console.log(phone);
                console.log(email);
                console.log('<?php echo $block->getFormKey() ?>');
                
                $.ajax({
                type: "POST",
                url: url + '?name=' + name  + '&mail=' + email + '&phone=' + phone + '&product_sku=' + sku,
                contentType: false,
                cache: false,
                processData: false,
                data: {form_key: '<?php echo $block->getFormKey() ?>'},
                
                success: function () {
                  $("#popup_modal").modal("closeModal");
                    console.log('dddddddddddd');
                },  

                error: function(XMLHttpRequest, textStatus, errorThrown) { 
                    alert("Status: " + textStatus); alert("Error: " + errorThrown); 
                },  

                showLoader: true
                });
                
            });
        }
    );
</script>